# Generated by Django 3.2 on 2022-04-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountinfo', '0002_students_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
